---
- name: Include distribution specific install tasks
  include: "install-{{ ansible_os_family }}.yml"

- name: Copy configuration file
  template:
    src: osquery.conf.j2
    dest: /etc/osquery/osquery.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart osquery service
  become: true
